apiVersion: apps/v1
kind: Deployment
metadata:
  name: colbyashi-maru-nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.digitalocean.com/devops-directive/colbyashi-maru-nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        imagePullPolicy: Always
            